#!/system/xbin/busybox sh

if [ ! -f "/data/synapse/stemp/rebootlate.lock" ]
then
    exit 0
fi

ZTIME="0"

if [ ! -f "/data/synapse/stemp/reboothours" ] || [ -z "$(busybox cat /data/synapse/stemp/reboothours)" ]
then
    busybox echo "1" > /data/synapse/stemp/reboothours
fi

if [ ! -f "/data/synapse/stemp/rebootmins" ] || [ -z "$(busybox cat /data/synapse/stemp/rebootmins)" ]
then
    busybox echo "0" > /data/synapse/stemp/rebootmins
fi

if [ "$(busybox cat /data/synapse/stemp/reboothours)" = "0" ] && [ "$(busybox cat /data/synapse/stemp/rebootmins)" = "0" ]
then
    rm /data/synapse/stemp/rebootlate.lock
    exit 0
fi

RAWHOURS="$(busybox cat /data/synapse/stemp/reboothours)"
HOURS=$(( RAWHOURS * 60 * 60))
RAWMINS="$(busybox cat /data/synapse/stemp/rebootmins)"
MINS=$(( RAWMINS * 60))
TIMEOUTVAL=$(( HOURS + MINS ))

if [ -z "$TIMEOUTVAL" ]
then
    TIMEOUTVAL="3600"
fi

if [ -f "/data/synapse/stemp/rebootlate.lock" ]
then
    while [ $TIMEOUTVAL -gt $ZTIME ]
    do
        if [ ! -f "/data/synapse/stemp/rebootlate.lock" ]
        then
            break
        fi
        busybox echo "$TIMEOUTVAL" > /data/synapse/stemp/rebootclock
        sleep 1
        TIMEOUTVAL=$(( TIMEOUTVAL - 1 ))
    done
fi

busybox echo "0" > /data/synapse/stemp/rebootclock

if [ -f "/data/synapse/stemp/rebootlate.lock" ]
then
    rm /data/synapse/stemp/rebootlate.lock &> /dev/null
    reboot
fi
