#!/system/bin/sh

if [ "$1" = "headphoneleft" ]
then
    LEFTVAL="$(busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$LEFTVAL" ]
        then
            busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1
        else
            busybox echo "$2 $(busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2)" > /sys/kernel/sound_control/headphone_gain
            busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1
        fi
    else
        busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1
    fi
elif [ "$1" = "headphoneright" ]
then
    RIGHTVAL="$(busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$RIGHTVAL" ]
        then
            busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2
        else
            busybox echo "$(busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1) $2" > /sys/kernel/sound_control/headphone_gain
            busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2
        fi
    else
        busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2
    fi
elif [ "$1" = "speaker_gain" ]
then
    SPKVAL="$(busybox cat /sys/kernel/sound_control/speaker_gain)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$SPKVAL" ]
        then
            busybox cat /sys/kernel/sound_control/speaker_gain
        else
            busybox echo "$2" > /sys/kernel/sound_control/speaker_gain
            busybox cat /sys/kernel/sound_control/speaker_gain
        fi
    else
        busybox cat /sys/kernel/sound_control/speaker_gain
    fi
elif [ "$1" = "mx_hw_eq" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/mx_hw_eq)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/mx_hw_eq
        else
            busybox echo "$2" > /sys/kernel/sound_control/mx_hw_eq
            busybox cat /sys/kernel/sound_control/mx_hw_eq
        fi
    else
        busybox cat /sys/kernel/sound_control/mx_hw_eq
    fi
elif [ "$1" = "iir1_gain" ]
then
    IIRGAIN="$(busybox cat /sys/kernel/sound_control/iir1_gain)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$IIRGAIN" ]
        then
            busybox cat /sys/kernel/sound_control/iir1_gain
        else
            busybox echo "$2" > /sys/kernel/sound_control/iir1_gain
            busybox cat /sys/kernel/sound_control/iir1_gain
        fi
    else
        busybox cat /sys/kernel/sound_control/iir1_gain
    fi
elif [ "$1" = "iir2_gain" ]
then
    IIRGAIN="$(busybox cat /sys/kernel/sound_control/iir2_gain)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$IIRGAIN" ]
        then
            busybox cat /sys/kernel/sound_control/iir2_gain
        else
            busybox echo "$2" > /sys/kernel/sound_control/iir2_gain
            busybox cat /sys/kernel/sound_control/iir2_gain
        fi
    else
        busybox cat /sys/kernel/sound_control/iir2_gain
    fi
elif [ "$1" = "usepagain" ]
then
    HPHENABLED="$(busybox cat /sys/kernel/sound_control/hph_pa_enabled)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$HPHENABLED" ]
        then
            busybox cat /sys/kernel/sound_control/hph_pa_enabled
        else
            busybox echo "$2" > /sys/kernel/sound_control/hph_pa_enabled
            busybox cat /sys/kernel/sound_control/hph_pa_enabled
        fi
    else
        busybox cat /sys/kernel/sound_control/hph_pa_enabled
    fi
elif [ "$1" = "force_hph_pa" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/force_hph_pa)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/force_hph_pa
        else
            busybox echo "$2" > /sys/kernel/sound_control/force_hph_pa
            busybox cat /sys/kernel/sound_control/force_hph_pa
        fi
    else
        busybox cat /sys/kernel/sound_control/force_hph_pa
    fi
elif [ "$1" = "pagainleft" ]
then
    LEFTVAL="$(busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 1)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$LEFTVAL" ]
        then
            busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 1
        else
            busybox echo "$2 $(busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 2)" > /sys/kernel/sound_control/hph_poweramp_gain
            busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 1
        fi
    else
        busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 1
    fi
elif [ "$1" = "pagainright" ]
then
    RIGHTVAL="$(busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 2)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$RIGHTVAL" ]
        then
            busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 2
        else
            busybox echo "$(busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 1) $2" > /sys/kernel/sound_control/hph_poweramp_gain
            busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 2
        fi
    else
        busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 2
    fi
elif [ "$1" = "highperfmode" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/high_perf_mode)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/high_perf_mode
        else
            busybox echo "$2" > /sys/kernel/sound_control/high_perf_mode
            busybox cat /sys/kernel/sound_control/high_perf_mode
        fi
    else
        busybox cat /sys/kernel/sound_control/high_perf_mode
    fi
elif [ "$1" = "uhqamode" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/uhqa_mode)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/uhqa_mode
        else
            busybox echo "$2" > /sys/kernel/sound_control/uhqa_mode
            busybox cat /sys/kernel/sound_control/uhqa_mode
        fi
    else
        busybox cat /sys/kernel/sound_control/uhqa_mode
    fi
elif [ "$1" = "autochopper" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/autochopper)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/autochopper
        else
            busybox echo "$2" > /sys/kernel/sound_control/autochopper
            busybox cat /sys/kernel/sound_control/autochopper
        fi
    else
        busybox cat /sys/kernel/sound_control/autochopper
    fi
elif [ "$1" = "chopbypass" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/chopper_bypass)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/chopper_bypass
        else
            busybox echo "$2" > /sys/kernel/sound_control/chopper_bypass
            busybox cat /sys/kernel/sound_control/chopper_bypass
        fi
    else
        busybox cat /sys/kernel/sound_control/chopper_bypass
    fi
elif [ "$1" = "anc_delay" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/anc_delay)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/anc_delay
        else
            busybox echo "$2" > /sys/kernel/sound_control/anc_delay
            busybox cat /sys/kernel/sound_control/anc_delay
        fi
    else
        busybox cat /sys/kernel/sound_control/anc_delay
    fi
elif [ "$1" = "headphone_left_hpf_bypass" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/headphone_left_hpf_bypass)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/headphone_left_hpf_bypass
        else
            busybox echo "$2" > /sys/kernel/sound_control/headphone_left_hpf_bypass
            busybox cat /sys/kernel/sound_control/headphone_left_hpf_bypass
        fi
    else
        busybox cat /sys/kernel/sound_control/headphone_left_hpf_bypass
    fi
elif [ "$1" = "headphone_right_hpf_bypass" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/headphone_right_hpf_bypass)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/headphone_right_hpf_bypass
        else
            busybox echo "$2" > /sys/kernel/sound_control/headphone_right_hpf_bypass
            busybox cat /sys/kernel/sound_control/headphone_right_hpf_bypass
        fi
    else
        busybox cat /sys/kernel/sound_control/headphone_right_hpf_bypass
    fi
elif [ "$1" = "speaker_hpf_bypass" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/speaker_hpf_bypass)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/speaker_hpf_bypass
        else
            busybox echo "$2" > /sys/kernel/sound_control/speaker_hpf_bypass
            busybox cat /sys/kernel/sound_control/speaker_hpf_bypass
        fi
    else
        busybox cat /sys/kernel/sound_control/speaker_hpf_bypass
    fi
elif [ "$1" = "interpolator_boost" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/interpolator_boost)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/interpolator_boost
        else
            busybox echo "$2" > /sys/kernel/sound_control/interpolator_boost
            busybox cat /sys/kernel/sound_control/interpolator_boost
        fi
    else
        busybox cat /sys/kernel/sound_control/interpolator_boost
    fi
elif [ "$1" = "interpolator_override" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/interpolator_override)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/interpolator_override
        else
            busybox echo "$2" > /sys/kernel/sound_control/interpolator_override
            busybox cat /sys/kernel/sound_control/interpolator_override
        fi
    else
        busybox cat /sys/kernel/sound_control/interpolator_override
    fi
elif [ "$1" = "compander_gain_lock" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/compander_gain_lock)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/compander_gain_lock
        else
            busybox echo "$2" > /sys/kernel/sound_control/compander_gain_lock
            busybox cat /sys/kernel/sound_control/compander_gain_lock
        fi
    else
        busybox cat /sys/kernel/sound_control/compander_gain_lock
    fi
elif [ "$1" = "compander_gain_boost" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/compander_gain_boost)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/compander_gain_boost
        else
            busybox echo "$2" > /sys/kernel/sound_control/compander_gain_boost
            busybox cat /sys/kernel/sound_control/compander_gain_boost
        fi
    else
        busybox cat /sys/kernel/sound_control/compander_gain_boost
    fi
elif [ "$1" = "wavegen_override" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/wavegen_override)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/wavegen_override
        else
            busybox echo "$2" > /sys/kernel/sound_control/wavegen_override
            busybox cat /sys/kernel/sound_control/wavegen_override
        fi
    else
        busybox cat /sys/kernel/sound_control/wavegen_override
    fi
elif [ "$1" = "headphone_hdc" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/headphone_hdc)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/headphone_hdc
        else
            busybox echo "$2" > /sys/kernel/sound_control/headphone_hdc
            busybox cat /sys/kernel/sound_control/headphone_hdc
        fi
    else
        busybox cat /sys/kernel/sound_control/headphone_hdc
    fi
elif [ "$1" = "speaker_hdc" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/speaker_hdc)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/speaker_hdc
        else
            busybox echo "$2" > /sys/kernel/sound_control/speaker_hdc
            busybox cat /sys/kernel/sound_control/speaker_hdc
        fi
    else
        busybox cat /sys/kernel/sound_control/speaker_hdc
    fi
elif [ "$1" = "speaker_mute" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/speaker_mute)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/speaker_mute
        else
            busybox echo "$2" > /sys/kernel/sound_control/speaker_mute
            busybox cat /sys/kernel/sound_control/speaker_mute
        fi
    else
        busybox cat /sys/kernel/sound_control/speaker_mute
    fi
elif [ "$1" = "headphone_mute" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/headphone_mute)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/headphone_mute
        else
            busybox echo "$2" > /sys/kernel/sound_control/headphone_mute
            busybox cat /sys/kernel/sound_control/headphone_mute
        fi
    else
        busybox cat /sys/kernel/sound_control/headphone_mute
    fi
elif [ "$1" = "headphone_left_hpf_cutoff" ]
then
    if [ -n "$2" ]
    then
        if [ "$2" = "4" ]
        then
            if [ "$(busybox cat /sys/kernel/sound_control/headphone_left_hpf_cutoff)" != "0" ]
            then
                busybox echo "0" > /sys/kernel/sound_control/headphone_left_hpf_cutoff
            fi
        elif [ "$2" = "75" ]
        then
            if [ "$(busybox cat /sys/kernel/sound_control/headphone_left_hpf_cutoff)" != "1" ]
            then
                busybox echo "1" > /sys/kernel/sound_control/headphone_left_hpf_cutoff
            fi
        elif [ "$2" = "150" ]
        then
            if [ "$(busybox cat /sys/kernel/sound_control/headphone_left_hpf_cutoff)" != "2" ]
            then
                busybox echo "2" > /sys/kernel/sound_control/headphone_left_hpf_cutoff
            fi
        fi
    fi

    if [ "$(busybox cat /sys/kernel/sound_control/headphone_left_hpf_cutoff)" = "0" ]
    then
        busybox echo "4"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_left_hpf_cutoff)" = "1" ]
    then
        busybox echo "75"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_left_hpf_cutoff)" = "2" ]
    then
        busybox echo "150"
    fi
elif [ "$1" = "headphone_right_hpf_cutoff" ]
then
    if [ -n "$2" ]
    then
        if [ "$2" = "4" ]
        then
            if [ "$(busybox cat /sys/kernel/sound_control/headphone_right_hpf_cutoff)" != "0" ]
            then
                busybox echo "0" > /sys/kernel/sound_control/headphone_right_hpf_cutoff
            fi
        elif [ "$2" = "75" ]
        then
            if [ "$(busybox cat /sys/kernel/sound_control/headphone_right_hpf_cutoff)" != "1" ]
            then
                busybox echo "1" > /sys/kernel/sound_control/headphone_right_hpf_cutoff
            fi
        elif [ "$2" = "150" ]
        then
            if [ "$(busybox cat /sys/kernel/sound_control/headphone_right_hpf_cutoff)" != "2" ]
            then
                busybox echo "2" > /sys/kernel/sound_control/headphone_right_hpf_cutoff
            fi
        fi
    fi

    if [ "$(busybox cat /sys/kernel/sound_control/headphone_right_hpf_cutoff)" = "0" ]
    then
        busybox echo "4"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_right_hpf_cutoff)" = "1" ]
    then
        busybox echo "75"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_right_hpf_cutoff)" = "2" ]
    then
        busybox echo "150"
    fi
elif [ "$1" = "speaker_hpf_cutoff" ]
then
    if [ -n "$2" ]
    then
        if [ "$2" = "4" ]
        then
            if [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" != "0" ]
            then
                busybox echo "0" > /sys/kernel/sound_control/speaker_hpf_cutoff
            fi
        elif [ "$2" = "75" ]
        then
            if [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" != "1" ]
            then
                busybox echo "1" > /sys/kernel/sound_control/speaker_hpf_cutoff
            fi
        elif [ "$2" = "150" ]
        then
            if [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" != "2" ]
            then
                busybox echo "2" > /sys/kernel/sound_control/speaker_hpf_cutoff
            fi
        fi
    fi

    if [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "0" ]
    then
        busybox echo "4"
    elif [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "1" ]
    then
        busybox echo "75"
    elif [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "2" ]
    then
        busybox echo "150"
    fi
elif [ "$1" = "peak_det_timeout" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/peak_det_timeout)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/peak_det_timeout
        else
            busybox echo "$2" > /sys/kernel/sound_control/peak_det_timeout
            busybox cat /sys/kernel/sound_control/peak_det_timeout
        fi
    else
        busybox cat /sys/kernel/sound_control/peak_det_timeout
    fi
elif [ "$1" = "rms_meter_div_fact" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/rms_meter_div_fact)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/rms_meter_div_fact
        else
            busybox echo "$2" > /sys/kernel/sound_control/rms_meter_div_fact
            busybox cat /sys/kernel/sound_control/rms_meter_div_fact
        fi
    else
        busybox cat /sys/kernel/sound_control/rms_meter_div_fact
    fi
elif [ "$1" = "rms_meter_resamp_fact" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/rms_meter_resamp_fact)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/rms_meter_resamp_fact
        else
            busybox echo "$2" > /sys/kernel/sound_control/rms_meter_resamp_fact
            busybox cat /sys/kernel/sound_control/rms_meter_resamp_fact
        fi
    else
        busybox cat /sys/kernel/sound_control/rms_meter_resamp_fact
    fi
elif [ "$1" = "hph_pa_bias" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/hph_pa_bias)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/hph_pa_bias
        else
            busybox echo "$2" > /sys/kernel/sound_control/hph_pa_bias
            busybox cat /sys/kernel/sound_control/hph_pa_bias
        fi
    else
        busybox cat /sys/kernel/sound_control/hph_pa_bias
    fi
elif [ "$1" = "cnp_bias" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/cnp_bias)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/cnp_bias
        else
            busybox echo "$2" > /sys/kernel/sound_control/cnp_bias
            busybox cat /sys/kernel/sound_control/cnp_bias
        fi
    else
        busybox cat /sys/kernel/sound_control/cnp_bias
    fi
elif [ "$1" = "compander1" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/compander1
elif [ "$1" = "hph_status" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/hph_status
elif [ "$1" = "headphone_audio_active" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/headphone_audio_active)"
    if [ -n "$2" ]
    then
        if [ "$CURVAL" = "1" ]
        then
            busybox echo "$2 Setting Locked"
        else
            busybox echo "$2 Setting Unlocked"
        fi
    else
        if [ "$CURVAL" = "1" ]
        then
            busybox echo "The Below Setting is Locked"
        else
            busybox echo "The Below Setting is Unlocked"
        fi
    fi
elif [ "$1" = "jack_locked" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/secjack_state)"
    if [ -n "$2" ]
    then
        if [ "$CURVAL" = "Unplugged" ]
        then
            busybox echo "$2 Setting Unlocked"
        else
            busybox echo "$2 Setting Locked"
        fi
    else
        if [ "$CURVAL" = "Unplugged" ]
        then
            busybox echo "The Below Setting is Unlocked"
        else
            busybox echo "The Below Setting is Locked"
        fi
    fi
elif [ "$1" = "compander_status" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/compander_enabled
elif [ "$1" = "class_h_control" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/class_h_control
elif [ "$1" = "autochopper_raw" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/autochopper_raw
elif [ "$1" = "chopper" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/chopper
elif [ "$1" = "iirs_locked" ]
then
    CURVAL="$(busybox cat /sys/kernel/sound_control/iirs_locked)"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox cat /sys/kernel/sound_control/iirs_locked
        else
            busybox echo "$2" > /sys/kernel/sound_control/iirs_locked
            busybox cat /sys/kernel/sound_control/iirs_locked
        fi
    else
        busybox cat /sys/kernel/sound_control/iirs_locked
    fi
elif [ "$1" = "headphone_dac_enabled" ]
then
    busybox cat /sys/kernel/sound_control/headphone_dac_enabled
elif [ "$1" = "secjack_state" ]
then
    busybox cat /sys/kernel/sound_control/secjack_state
fi
